#!/bin/bash
#########################################################################
# File Name: /usr/local/bin/tscp.sh
# Author: juson
# mail: jusonlinux@163.com
# Created Time: 2015年12月16日 星期三 13时08分50秒
#########################################################################
src_file=""
yes=0
rmhost="jiafd@121.199.42.40:"
basedir="/data"

while [ -n "$1" ]
do
	case $1 in
		'-d')
			basedir=$2; shift 2
			;;
		'-o')
			option=$2; shift 2
			;;
		'-y')
			yes=1; shift
			;;
		'-ps')
			rmhost="jiafd@182.92.184.96:"; shift
			;;
		'-ps51')
			rmhost="jiafd@123.56.159.51:"; shift
			;;
		'-ps60')
			rmhost="jiafd@101.201.76.60:"; shift
			;;
		*)
			src_file="$src_file $1"; shift
		;;
	esac
done

#if [ ! -f "$src_file" ]; then
#	echo "Terminating, $src_file not exits."; exit
#fi

optStr=""
for src_f in $src_file 
do
	src_f=${src_f%/}
	dir=${src_f%/*}
	if echo $optStr | grep ">>>>"$dir"|" > /dev/null; then
		#存在同级目录文件,追加
		optStr=${optStr/$dir"|"/$src_f">>>>"$dir"|"}
	else
		optStr=${src_f}">>>>"$dir"|"$optStr                                                                    
	fi
done

if [ "$option" == "lv2ls" ]; then
	#本地svn到本地服务器
	cmd="cp -r"
	from_format="\$sig_file"
	to_format="${basedir}/\$sig_file"
elif [ "$option" == "lv2ts" ]; then
	#本地svn到测试服务器
	cmd="scp -r"
	from_format="\$sig_file"
	to_format=$rmhost"${basedir}/"\${sig_file/web/www/html}
else
	echo "Terminating, unknown commond!"; exit
fi

cmd_list=${optStr//|/" "}
for org_cmd in $cmd_list
do
	tmp_cmd=${org_cmd//>>>>/" "}
	from_files=${tmp_cmd% *}
	to_file=${tmp_cmd##* }
	rel_files=""
	for sig_file in $from_files
	do
		rel_file=$(eval "echo $from_format")
		rel_files="$rel_files $rel_file"
	done

	sig_file=$to_file
	to_file=$(eval "echo $to_format")
	echo "$cmd $rel_files $to_file"

	if [ "$yes" == "0" ]; then
		read -p "确定执行拷贝？[y/n]" confirm 
	else
		confirm='y'
	fi
	if [ "$confirm" == 'y' ]; then 
		$cmd $rel_files $to_file;                                              
	fi
done
